# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7539a4ae653910e7ffd8465c0e9cb6adccdce4d4cb4a44a2f4a54d1b04b2122c9c5b75be8d9d92a32235e0bd08802628f9d53e94f89557207ca332ec95323ea4

test:
  secret_key_base: 16daea0094c6d0ff2299d25877c18fde139994084e4f3f45d3e49d05e8f01fb24f8c37e3c43a6142147ff090b51f813d8f91c5b5669a27a4db96d2ecec471efa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
